# load(":sparse_git.bzl", "sparse_git_repo")

# sparse_git_repo(
#     name = "libshared",
#     path = "./libshared"
# )

# sparse_git_repo(
#     name = "libcore",
#     path = "./libcore"
# )

# sparse_cone(name = "libshared")
# sparse_cone(name = "libcore")